---
# tasks file for nginx
- name: add the nginx repository
  yum_repository:
    name: nginx
    description: nginx CentOS repo
    baseurl: http://nginx.org/packages/centos/$releasever/$basearch/
    gpgkey: https://nginx.org/keys/nginx_signing.key
    gpgcheck: True

- name: install nginx
  yum:
    name:
      - nginx
    state: present

- name: enable nginx
  service:
    name: nginx
    enabled: yes

- name: set up sites-available config directory
  file:
    path: /etc/nginx/sites-available
    state: directory

- name: set up sites-enabled config directory
  file:
    path: /etc/nginx/sites-enabled
    state: directory

- name: write nginx config
  template: dest=/etc/nginx/nginx.conf src={{ nginx_conf_template }}
  notify: reload nginx

- name: write default nginx config
  template: dest=/etc/nginx/sites-available/default.conf src={{ nginx_default_host }}

- name: remove junk file
  file:
    path: /etc/nginx/sites-available/default.config
    state: absent

- name: add enabled site symlinks
  file:
    path: '{{ nginx_sites_enabled }}{{ item }}.conf'
    src: '{{ nginx_sites_available }}{{ item }}.conf'
    state: link
  with_items:
      - default
  notify: reload nginx

# commented because there is nothing to disable
# - name: remove disabled site symlinks
#   file:
#     path: '{{ nginx_sites_enabled }}{{ item }}.conf'
#     state: absent
#   with_items:
#   notify: reload nginx
