- name: install php
  yum:
    name:
      - php73
      - php73-php-cli
      - php73-php-common
      - php73-php-fpm
      - php73-php-json
      - php73-php-ldap
      - php73-php-mbstring
      - php73-php-mysqlnd
      - php73-php-opcache
      - php73-php-pecl-mysql
      - php73-php-pecl-redis4
      - php73-php-xml
    state: present
